In [84]:
import pandas as pd
import zipfile

In [130]:
vax_percent_df = pd.read_csv("County - Table_data.csv")

percent_ovr_65_df = pd.read_csv("Pop over 65%.csv",skiprows=4)

with zipfile.ZipFile('AHRF_CSV_2022-2023.zip', 'r') as z:
    with z.open('AHRF_CSV_2022-2023/DATA/ahrf2023.csv') as f:
        ahrf_df = pd.read_csv(f, encoding='latin1', low_memory=False)

In [131]:
vax_percent_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 714 entries, 0 to 713
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Jurisdiction    714 non-null    str
 1   Measure Names   714 non-null    str
 2   Measure Values  712 non-null    float64
dtypes: float64(1), str(2)
memory usage: 16.9 KB

In [132]:
unique_measures = vax_percent_df['Measure Names'].unique()
print(unique_measures)

<StringArray>
[                    '7-Day Doses Administered',
 'Percent of Population Completing Vaccination',
 'Percent of Population Initiating Vaccination',
           'COVID-19 Vaccine Regimen Completed',
           'COVID-19 Vaccine Regimen Initiated',
                     'Total Doses Administered']
Length: 6, dtype: str

In [133]:
completing_measure = ['Percent of Population Completing Vaccination']
vax_percent_complete_df = vax_percent_df[vax_percent_df['Measure Names'].isin(completing_measure)].copy()

In [134]:
vax_percent_complete_df = (vax_percent_complete_df.drop(columns=['Measure Names']).rename(columns = {'Measure Values': 'Percent of Population Completing Vaccination'}).reset_index(drop=True))

In [135]:
vax_percent_complete_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 2 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Jurisdiction                                  119 non-null    str
 1   Percent of Population Completing Vaccination  118 non-null    float64
dtypes: float64(1), str(1)
memory usage: 2.0 KB

In [136]:
unique_measures = vax_percent_complete_df['Jurisdiction'].unique()
print(unique_measures)

<StringArray>
[              'Wright',                'Worth',              'Webster',
                'Wayne',           'Washington',               'Warren',
               'Vernon', 'Unknown Jurisdiction',                'Texas',
                'Taney',
 ...
                'Boone',            'Bollinger',               'Benton',
                'Bates',               'Barton',                'Barry',
              'Audrain',             'Atchison',               'Andrew',
                'Adair']
Length: 119, dtype: str

In [137]:
vax_complete_cleaned = vax_percent_complete_df.dropna()
vax_complete_cleaned.info()

<class 'pandas.DataFrame'>
Index: 118 entries, 0 to 118
Data columns (total 2 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Jurisdiction                                  118 non-null    str
 1   Percent of Population Completing Vaccination  118 non-null    float64
dtypes: float64(1), str(1)
memory usage: 2.8 KB

In [138]:
vax_complete_cleaned

    Jurisdiction  Percent of Population Completing Vaccination
0         Wright                                      0.375800
1          Worth                                      0.401391
2        Webster                                      0.413594
3          Wayne                                      0.320360
4     Washington                                      0.361868
..           ...                                           ...
114        Barry                                      0.416972
115      Audrain                                      0.405034
116     Atchison                                      0.580789
117       Andrew                                      0.478884
118        Adair                                      0.495285

[118 rows x 2 columns]

In [139]:
initiating_measure = ['Percent of Population Initiating Vaccination']
vax_percent_initiate_df = vax_percent_df[vax_percent_df['Measure Names'].isin(initiating_measure)].copy()

In [140]:
vax_percent_initiate_df = (vax_percent_initiate_df.drop(columns=['Measure Names']).rename(columns = {'Measure Values': 'Percent of Population Initiating Vaccination'}).reset_index(drop=True))

In [141]:
vax_percent_initiate_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 2 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Jurisdiction                                  119 non-null    str
 1   Percent of Population Initiating Vaccination  118 non-null    float64
dtypes: float64(1), str(1)
memory usage: 2.0 KB

In [142]:
unique_measures = vax_percent_initiate_df['Jurisdiction'].unique()
print(unique_measures)

<StringArray>
[              'Wright',                'Worth',              'Webster',
                'Wayne',           'Washington',               'Warren',
               'Vernon', 'Unknown Jurisdiction',                'Texas',
                'Taney',
 ...
                'Boone',            'Bollinger',               'Benton',
                'Bates',               'Barton',                'Barry',
              'Audrain',             'Atchison',               'Andrew',
                'Adair']
Length: 119, dtype: str

In [143]:
vax_initiate_cleaned = vax_percent_initiate_df.dropna()
vax_initiate_cleaned.info()

<class 'pandas.DataFrame'>
Index: 118 entries, 0 to 118
Data columns (total 2 columns):
 #   Column                                        Non-Null Count  Dtype
---  ------                                        --------------  -----
 0   Jurisdiction                                  118 non-null    str
 1   Percent of Population Initiating Vaccination  118 non-null    float64
dtypes: float64(1), str(1)
memory usage: 2.8 KB

In [144]:
vax_initiate_cleaned

    Jurisdiction  Percent of Population Initiating Vaccination
0         Wright                                      0.409208
1          Worth                                      0.433184
2        Webster                                      0.444913
3          Wayne                                      0.350113
4     Washington                                      0.397816
..           ...                                           ...
114        Barry                                      0.464752
115      Audrain                                      0.450173
116     Atchison                                      0.597317
117       Andrew                                      0.495314
118        Adair                                      0.527009

[118 rows x 2 columns]

In [145]:
ahrf_df

,blank,fips_st_cnty,entity_file,secndry_entity_file,date_file,date_cretn,file_length,st_name,st_name_abbrev,cnty_name,...,dys_air_qulty_mesrd_21,dys_mesrd_air_qulty_good_22,dys_mesrd_air_qulty_good_21,good_air_qulty_dys_pct_22,good_air_qulty_dys_pct_21,annul_partclt_mattr_2_5_avg_19,annul_partclt_mattr_2_5_avg_18,dys_8_hr_ozone_over_naaqs_avg_19,dys_8_hr_ozone_over_naaqs_avg_18,elevtn_feet_76
0,NaN,1001,AHRF,1001,2023,23208,25907,Alabama,AL,Autauga,...,NaN,NaN,NaN,NaN,NaN,10.0,9.5,1.0,0.0,290.0
1,NaN,1003,AHRF,1003,2023,23208,25907,Alabama,AL,Baldwin,...,280.0,256.0,264.0,91.10,94.29,7.6,7.2,0.0,0.0,155.0
2,NaN,1005,AHRF,1005,2023,23208,25907,Alabama,AL,Barbour,...,NaN,NaN,NaN,NaN,NaN,9.4,9.0,0.0,0.0,220.0
3,NaN,1007,AHRF,1007,2023,23208,25907,Alabama,AL,Bibb,...,NaN,NaN,NaN,NaN,NaN,9.8,9.4,0.0,1.0,224.0
4,NaN,1009,AHRF,1009,2023,23208,25907,Alabama,AL,Blount,...,NaN,NaN,NaN,NaN,NaN,9.6,9.4,1.0,1.0,870.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3226,NaN,72151,AHRF,72151,2023,23208,25907,Puerto Rico,PR,Yabucoa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3227,NaN,72153,AHRF,72153,2023,23208,25907,Puerto Rico,PR,Yauco,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3228,NaN,78010,AHRF,78010,2023,23208,25907,US Virgin Islands,VI,St. Croix,...,55.0,23.0,52.0,88.46,94.55,6.3,NaN,NaN,NaN,NaN
3229,NaN,78020,AHRF,78020,2023,23208,25907,US Virgin Islands,VI,St. John,...,45.0,69.0,44.0,87.34,97.78,NaN,NaN,NaN,NaN,NaN
3230,NaN,78030,AHRF,78030,2023,23208,25907,US Virgin Islands,VI,St. Thomas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [146]:
ahrf_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 3231 entries, 0 to 3230
Columns: 4306 entries, blank to elevtn_feet_76
dtypes: float64(4286), int64(9), str(11)
memory usage: 106.1 MB

In [147]:
ahrf_df.columns.tolist()

['blank',
 'fips_st_cnty',
 'entity_file',
 'secndry_entity_file',
 'date_file',
 'date_cretn',
 'file_length',
 'st_name',
 'st_name_abbrev',
 'cnty_name',
 'cnty_name_st_abbrev',
 'fips_st',
 'fips_cnty',
 'cens_regn',
 'cens_regn_name',
 'cens_divsn',
 'cens_divsn_name',
 'fed_regn',
 'ssa_benfcry',
 'cbsa_20',
 'cbsa_name_20',
 'cbsa_ind_20',
 'cbsa_cnty_stats_20',
 'metro_divsn_20',
 'metro_divsn_name_20',
 'combnd_stat_area_20',
 'combnd_stat_area_name_20',
 'rural_urban_contnm_13',
 'urban_influnc_13',
 'econ_depndnt_typolgy_15',
 'farmng_depndnt_typolgy_15',
 'minng_depndnt_typolgy_15',
 'mfg_depndnt_typolgy_15',
 'fed_st_govt_depndnt_typolgy_15',
 'recrtn_typolgy_15',
 'nonspclzd_depndnt_typolgy_15',
 'lo_eductn_typolgy_15',
 'lo_emplymt_typolgy_15',
 'hi_povty_typolgy_14',
 'prstnt_povty_typolgy_14',
 'prstnt_child_povty_typolgy_15',
 'popn_loss_typolgy_15',
 'retrmnt_destntn_typolgy_15',
 'hpsa_prim_care_23',
 'hpsa_prim_care_22',
 'hpsa_dent_23',
 'hpsa_dent_22',
 'hpsa_mentl_hlth_23',
 'hpsa_mentl_hlth_22',
 'contgs_cnty_num01',
 'contgs_cnty_num02',
 'contgs_cnty_num03',
 'contgs_cnty_num04',
 'contgs_cnty_num05',
 'contgs_cnty_num06',
 'contgs_cnty_num07',
 'contgs_cnty_num08',
 'contgs_cnty_num09',
 'contgs_cnty_num10',
 'contgs_cnty_num11',
 'contgs_cnty_num12',
 'contgs_cnty_num13',
 'contgs_cnty_num14',
 'phys_nf_prim_care_pc_exc_rsdt_21',
 'phys_nf_prim_care_pc_exc_rsdt_20',
 'phys_nf_prim_care_pc_rsdnt_21',
 'phys_nf_prim_care_pc_rsdnt_20',
 'md_nf_prim_care_pc_excl_rsdnt_21',
 'md_nf_prim_care_pc_excl_rsdnt_20',
 'md_nf_prim_care_pc_rsdnt_21',
 'md_nf_prim_care_pc_rsdnt_20',
 'do_nf_prim_care_pc_excl_rsdnt_21',
 'do_nf_prim_care_pc_excl_rsdnt_20',
 'do_nf_prim_care_pc_rsdnt_21',
 'do_nf_prim_care_pc_rsdnt_20',
 'md_nf_fed_activ_21',
 'md_nf_fed_activ_20',
 'md_nf_activ_21',
 'md_nf_activ_20',
 'md_nf_fed_21',
 'md_nf_fed_20',
 'md_nf_21',
 'md_nf_20',
 'md_nf_all_pc_21',
 'md_nf_all_pc_20',
 'md_nf_pc_ofc_21',
 'md_nf_pc_ofc_20',
 'md_nf_pc_hosp_all_21',
 'md_nf_pc_hosp_all_20',
 'md_nf_pc_rsdnt_21',
 'md_nf_pc_rsdnt_20',
 'md_nf_pc_hosp_ft_21',
 'md_nf_pc_hosp_ft_20',
 'md_nf_othprofl_21',
 'md_nf_othprofl_20',
 'md_nf_admin_21',
 'md_nf_admin_20',
 'md_nf_teach_21',
 'md_nf_teach_20',
 'md_nf_resrch_21',
 'md_nf_resrch_20',
 'md_nf_oth_21',
 'md_nf_oth_20',
 'md_nf_all_gp_21',
 'md_nf_all_gp_20',
 'md_nf_all_gp_all_pc_21',
 'md_nf_all_gp_all_pc_20',
 'md_nf_all_gp_pc_ofc_21',
 'md_nf_all_gp_pc_ofc_20',
 'md_nf_all_gp_pc_rsdnt_21',
 'md_nf_all_gp_pc_rsdnt_20',
 'md_nf_all_gp_pc_hosp_ft_21',
 'md_nf_all_gp_pc_hosp_ft_20',
 'md_nf_all_gp_admin_21',
 'md_nf_all_gp_admin_20',
 'md_nf_all_gp_teach_21',
 'md_nf_all_gp_teach_20',
 'md_nf_all_gp_resrch_21',
 'md_nf_all_gp_resrch_20',
 'md_nf_all_gp_oth_21',
 'md_nf_all_gp_oth_20',
 'md_nf_gp_21',
 'md_nf_gp_20',
 'md_nf_gp_all_pc_21',
 'md_nf_gp_all_pc_20',
 'md_nf_gp_pc_ofc_21',
 'md_nf_gp_pc_ofc_20',
 'md_nf_gp_pc_rsdnt_21',
 'md_nf_gp_pc_rsdnt_20',
 'md_nf_gp_pc_hosp_ft_21',
 'md_nf_gp_pc_hosp_ft_20',
 'md_nf_gp_admin_21',
 'md_nf_gp_admin_20',
 'md_nf_gp_teach_21',
 'md_nf_gp_teach_20',
 'md_nf_gp_resrch_21',
 'md_nf_gp_resrch_20',
 'md_nf_gp_oth_21',
 'md_nf_gp_oth_20',
 'md_nf_fammed_gen_21',
 'md_nf_fammed_gen_20',
 'md_nf_fammed_gen_all_pc_21',
 'md_nf_fammed_gen_all_pc_20',
 'md_nf_fammed_gen_pc_ofc_21',
 'md_nf_fammed_gen_pc_ofc_20',
 'md_nf_fammed_gen_pc_rsdnt_21',
 'md_nf_fammed_gen_pc_rsdnt_20',
 'md_nf_fammed_gen_pc_hosp_ft_21',
 'md_nf_fammed_gen_pc_hosp_ft_20',
 'md_nf_fammed_gen_admin_21',
 'md_nf_fammed_gen_admin_20',
 'md_nf_fammed_gen_teach_21',
 'md_nf_fammed_gen_teach_20',
 'md_nf_fammed_gen_resrch_21',
 'md_nf_fammed_gen_resrch_20',
 'md_nf_fammed_gen_oth_21',
 'md_nf_fammed_gen_oth_20',
 'md_nf_fammed_subsp_21',
 'md_nf_fammed_subsp_20',
 'md_nf_fammed_subsp_all_pc_21',
 'md_nf_fammed_subsp_all_pc_20',
 'md_nf_fammed_subsp_pc_ofc_21',
 'md_nf_fammed_subsp_pc_ofc_20',
 'md_nf_fammed_subsp_pc_rsdnt_21',
 'md_nf_fammed_subsp_pc_rsdnt_20',
 'md_nf_fammed_subsp_pc_hosp_ft_21',
 'md_nf_fammed_subsp_pc_hosp_ft_20',
 'md_nf_fammed_subsp_admin_21',
 'md_nf_fammed_subsp_admin_20',
 'md_nf_fammed_subsp_teach_21',
 'md_nf_fammed_subsp_teach_20',
 'md_nf_fammed_subsp_resrch_21',
 'md_nf_fammed_subsp_resrch_20',
 'md_nf_fammed_subsp_oth_21',
 'md_nf_fammed_subsp_oth_20',
 'md_nf_all_med_spec_21',
 'md_nf_all_med_spec_20',
 'md_nf_all_med_spec_all_pc_21',
 'md_nf_all_med_spec_all_pc_20',
 'md_nf_all_med_spec_pc_ofc_21',
 'md_nf_all_med_spec_pc_ofc_20',
 'md_nf_all_med_spec_pc_rsdnt_21',
 'md_nf_all_med_spec_pc_rsdnt_20',
 'md_nf_all_med_spec_pc_hosp_ft_21',
 'md_nf_all_med_spec_pc_hosp_ft_20',
 'md_nf_all_med_spec_admin_21',
 'md_nf_all_med_spec_admin_20',
 'md_nf_all_med_spec_teach_21',
 'md_nf_all_med_spec_teach_20',
 'md_nf_all_med_spec_resrch_21',
 'md_nf_all_med_spec_resrch_20',
 'md_nf_all_med_spec_oth_21',
 'md_nf_all_med_spec_oth_20',
 'md_nf_allergy_21',
 'md_nf_allergy_20',
 'md_nf_allergy_all_pc_21',
 'md_nf_allergy_all_pc_20',
 'md_nf_allergy_pc_ofc_21',
 'md_nf_allergy_pc_ofc_20',
 'md_nf_allergy_pc_rsdnt_21',
 'md_nf_allergy_pc_rsdnt_20',
 'md_nf_allergy_pc_hosp_ft_21',
 'md_nf_allergy_pc_hosp_ft_20',
 'md_nf_allergy_admin_21',
 'md_nf_allergy_admin_20',
 'md_nf_allergy_teach_21',
 'md_nf_allergy_teach_20',
 'md_nf_allergy_resrch_21',
 'md_nf_allergy_resrch_20',
 'md_nf_allergy_oth_21',
 'md_nf_allergy_oth_20',
 'md_nf_card_dis_21',
 'md_nf_card_dis_20',
 'md_nf_card_dis_all_pc_21',
 'md_nf_card_dis_all_pc_20',
 'md_nf_card_dis_pc_ofc_21',
 'md_nf_card_dis_pc_ofc_20',
 'md_nf_card_dis_pc_rsdnt_21',
 'md_nf_card_dis_pc_rsdnt_20',
 'md_nf_card_dis_pc_hosp_ft_21',
 'md_nf_card_dis_pc_hosp_ft_20',
 'md_nf_card_dis_admin_21',
 'md_nf_card_dis_admin_20',
 'md_nf_card_dis_teach_21',
 'md_nf_card_dis_teach_20',
 'md_nf_card_dis_resrch_21',
 'md_nf_card_dis_resrch_20',
 'md_nf_card_dis_oth_21',
 'md_nf_card_dis_oth_20',
 'md_nf_derm_21',
 'md_nf_derm_20',
 'md_nf_derm_all_pc_21',
 'md_nf_derm_all_pc_20',
 'md_nf_derm_pc_ofc_21',
 'md_nf_derm_pc_ofc_20',
 'md_nf_derm_pc_rsdnt_21',
 'md_nf_derm_pc_rsdnt_20',
 'md_nf_derm_pc_hosp_ft_21',
 'md_nf_derm_pc_hosp_ft_20',
 'md_nf_derm_admin_21',
 'md_nf_derm_admin_20',
 'md_nf_derm_teach_21',
 'md_nf_derm_teach_20',
 'md_nf_derm_resrch_21',
 'md_nf_derm_resrch_20',
 'md_nf_derm_oth_21',
 'md_nf_derm_oth_20',
 'md_nf_gastr_21',
 'md_nf_gastr_20',
 'md_nf_gastr_all_pc_21',
 'md_nf_gastr_all_pc_20',
 'md_nf_gastr_pc_ofc_21',
 'md_nf_gastr_pc_ofc_20',
 'md_nf_gastr_pc_rsdnt_21',
 'md_nf_gastr_pc_rsdnt_20',
 'md_nf_gastr_pc_hosp_ft_21',
 'md_nf_gastr_pc_hosp_ft_20',
 'md_nf_gastr_admin_21',
 'md_nf_gastr_admin_20',
 'md_nf_gastr_teach_21',
 'md_nf_gastr_teach_20',
 'md_nf_gastr_resrch_21',
 'md_nf_gastr_resrch_20',
 'md_nf_gastr_oth_21',
 'md_nf_gastr_oth_20',
 'md_nf_genintmed_21',
 'md_nf_genintmed_20',
 'md_nf_genintmed_all_pc_21',
 'md_nf_genintmed_all_pc_20',
 'md_nf_genintmed_pc_ofc_21',
 'md_nf_genintmed_pc_ofc_20',
 'md_nf_genintmed_pc_rsdnt_21',
 'md_nf_genintmed_pc_rsdnt_20',
 'md_nf_genintmed_pc_hosp_ft_21',
 'md_nf_genintmed_pc_hosp_ft_20',
 'md_nf_genintmed_admin_21',
 'md_nf_genintmed_admin_20',
 'md_nf_genintmed_teach_21',
 'md_nf_genintmed_teach_20',
 'md_nf_genintmed_resrch_21',
 'md_nf_genintmed_resrch_20',
 'md_nf_genintmed_oth_21',
 'md_nf_genintmed_oth_20',
 'md_nf_intmed_subsp_21',
 'md_nf_intmed_subsp_20',
 'md_nf_intmed_subsp_all_pc_21',
 'md_nf_intmed_subsp_all_pc_20',
 'md_nf_intmed_subsp_pc_ofc_21',
 'md_nf_intmed_subsp_pc_ofc_20',
 'md_nf_intmed_subsp_pc_rsdnt_21',
 'md_nf_intmed_subsp_pc_rsdnt_20',
 'md_nf_intmed_subsp_pc_hosp_ft_21',
 'md_nf_intmed_subsp_pc_hosp_ft_20',
 'md_nf_intmed_subsp_admin_21',
 'md_nf_intmed_subsp_admin_20',
 'md_nf_intmed_subsp_teach_21',
 'md_nf_intmed_subsp_teach_20',
 'md_nf_intmed_subsp_resrch_21',
 'md_nf_intmed_subsp_resrch_20',
 'md_nf_intmed_subsp_oth_21',
 'md_nf_intmed_subsp_oth_20',
 'md_nf_ped_gen_21',
 'md_nf_ped_gen_20',
 'md_nf_ped_gen_all_pc_21',
 'md_nf_ped_gen_all_pc_20',
 'md_nf_ped_gen_pc_ofc_21',
 'md_nf_ped_gen_pc_ofc_20',
 'md_nf_ped_gen_pc_rsdnt_21',
 'md_nf_ped_gen_pc_rsdnt_20',
 'md_nf_ped_gen_pc_hosp_ft_21',
 'md_nf_ped_gen_pc_hosp_ft_20',
 'md_nf_ped_gen_admin_21',
 'md_nf_ped_gen_admin_20',
 'md_nf_ped_gen_teach_21',
 'md_nf_ped_gen_teach_20',
 'md_nf_ped_gen_resrch_21',
 'md_nf_ped_gen_resrch_20',
 'md_nf_ped_gen_oth_21',
 'md_nf_ped_gen_oth_20',
 'md_nf_ped_subsp_21',
 'md_nf_ped_subsp_20',
 'md_nf_ped_subsp_all_pc_21',
 'md_nf_ped_subsp_all_pc_20',
 'md_nf_ped_subsp_pc_ofc_21',
 'md_nf_ped_subsp_pc_ofc_20',
 'md_nf_ped_subsp_pc_rsdnt_21',
 'md_nf_ped_subsp_pc_rsdnt_20',
 'md_nf_ped_subsp_pc_hosp_ft_21',
 'md_nf_ped_subsp_pc_hosp_ft_20',
 'md_nf_ped_subsp_admin_21',
 'md_nf_ped_subsp_admin_20',
 'md_nf_ped_subsp_teach_21',
 'md_nf_ped_subsp_teach_20',
 'md_nf_ped_subsp_resrch_21',
 'md_nf_ped_subsp_resrch_20',
 'md_nf_ped_subsp_oth_21',
 'md_nf_ped_subsp_oth_20',
 'md_nf_ped_card_21',
 'md_nf_ped_card_20',
 'md_nf_ped_card_all_pc_21',
 'md_nf_ped_card_all_pc_20',
 'md_nf_ped_card_pc_ofc_21',
 'md_nf_ped_card_pc_ofc_20',
 'md_nf_ped_card_pc_rsdnt_21',
 'md_nf_ped_card_pc_rsdnt_20',
 'md_nf_ped_card_pc_hosp_ft_21',
 'md_nf_ped_card_pc_hosp_ft_20',
 'md_nf_ped_card_admin_21',
 'md_nf_ped_card_admin_20',
 'md_nf_ped_card_teach_21',
 'md_nf_ped_card_teach_20',
 'md_nf_ped_card_resrch_21',
 'md_nf_ped_card_resrch_20',
 'md_nf_ped_card_oth_21',
 'md_nf_ped_card_oth_20',
 'md_nf_pulm_dis_21',
 'md_nf_pulm_dis_20',
 'md_nf_pulm_dis_all_pc_21',
 'md_nf_pulm_dis_all_pc_20',
 'md_nf_pulm_dis_pc_ofc_21',
 'md_nf_pulm_dis_pc_ofc_20',
 'md_nf_pulm_dis_pc_rsdnt_21',
 'md_nf_pulm_dis_pc_rsdnt_20',
 'md_nf_pulm_dis_pc_hosp_ft_21',
 'md_nf_pulm_dis_pc_hosp_ft_20',
 'md_nf_pulm_dis_admin_21',
 'md_nf_pulm_dis_admin_20',
 'md_nf_pulm_dis_teach_21',
 'md_nf_pulm_dis_teach_20',
 'md_nf_pulm_dis_resrch_21',
 'md_nf_pulm_dis_resrch_20',
 'md_nf_pulm_dis_oth_21',
 'md_nf_pulm_dis_oth_20',
 'md_nf_all_surg_spec_21',
 'md_nf_all_surg_spec_20',
 'md_nf_all_surg_spec_all_pc_21',
 'md_nf_all_surg_spec_all_pc_20',
 'md_nf_all_surg_spec_pc_ofc_21',
 'md_nf_all_surg_spec_pc_ofc_20',
 'md_nf_all_surg_spec_pc_rsdnt_21',
 'md_nf_all_surg_spec_pc_rsdnt_20',
 'md_nf_all_surg_spc_pc_hosp_ft_21',
 'md_nf_all_surg_spc_pc_hosp_ft_20',
 'md_nf_all_surg_spec_admin_21',
 'md_nf_all_surg_spec_admin_20',
 'md_nf_all_surg_spec_teach_21',
 'md_nf_all_surg_spec_teach_20',
 'md_nf_all_surg_spec_resrch_21',
 'md_nf_all_surg_spec_resrch_20',
 'md_nf_all_surg_spec_oth_21',
 'md_nf_all_surg_spec_oth_20',
 'md_nf_gen_surg_21',
 'md_nf_gen_surg_20',
 'md_nf_gen_surg_all_pc_21',
 'md_nf_gen_surg_all_pc_20',
 'md_nf_gen_surg_pc_ofc_21',
 'md_nf_gen_surg_pc_ofc_20',
 'md_nf_gen_surg_pc_rsdnt_21',
 'md_nf_gen_surg_pc_rsdnt_20',
 'md_nf_gen_surg_pc_hosp_ft_21',
 'md_nf_gen_surg_pc_hosp_ft_20',
 'md_nf_gen_surg_admin_21',
 'md_nf_gen_surg_admin_20',
 'md_nf_gen_surg_teach_21',
 'md_nf_gen_surg_teach_20',
 'md_nf_gen_surg_resrch_21',
 'md_nf_gen_surg_resrch_20',
 'md_nf_gen_surg_oth_21',
 'md_nf_gen_surg_oth_20',
 'md_nf_neuro_surg_21',
 'md_nf_neuro_surg_20',
 'md_nf_neuro_surg_all_pc_21',
 'md_nf_neuro_surg_all_pc_20',
 'md_nf_neuro_surg_pc_ofc_21',
 'md_nf_neuro_surg_pc_ofc_20',
 'md_nf_neuro_surg_pc_rsdnt_21',
 'md_nf_neuro_surg_pc_rsdnt_20',
 'md_nf_neuro_surg_pc_hosp_ft_21',
 'md_nf_neuro_surg_pc_hosp_ft_20',
 'md_nf_neuro_surg_admin_21',
 'md_nf_neuro_surg_admin_20',
 'md_nf_neuro_surg_teach_21',
 'md_nf_neuro_surg_teach_20',
 'md_nf_neuro_surg_resrch_21',
 'md_nf_neuro_surg_resrch_20',
 'md_nf_neuro_surg_oth_21',
 'md_nf_neuro_surg_oth_20',
 'md_nf_obgyn_gen_21',
 'md_nf_obgyn_gen_20',
 'md_nf_obgyn_gen_all_pc_21',
 'md_nf_obgyn_gen_all_pc_20',
 'md_nf_obgyn_gen_pc_ofc_21',
 'md_nf_obgyn_gen_pc_ofc_20',
 'md_nf_obgyn_gen_pc_rsdnt_21',
 'md_nf_obgyn_gen_pc_rsdnt_20',
 'md_nf_obgyn_gen_pc_hosp_ft_21',
 'md_nf_obgyn_gen_pc_hosp_ft_20',
 'md_nf_obgyn_gen_admin_21',
 'md_nf_obgyn_gen_admin_20',
 'md_nf_obgyn_gen_teach_21',
 'md_nf_obgyn_gen_teach_20',
 'md_nf_obgyn_gen_resrch_21',
 'md_nf_obgyn_gen_resrch_20',
 'md_nf_obgyn_gen_oth_21',
 'md_nf_obgyn_gen_oth_20',
 'md_nf_obgyn_subsp_21',
 'md_nf_obgyn_subsp_20',
 'md_nf_obgyn_subsp_all_pc_21',
 'md_nf_obgyn_subsp_all_pc_20',
 'md_nf_obgyn_subsp_pc_ofc_21',
 'md_nf_obgyn_subsp_pc_ofc_20',
 'md_nf_obgyn_subsp_pc_rsdnt_21',
 'md_nf_obgyn_subsp_pc_rsdnt_20',
 'md_nf_obgyn_subsp_pc_hosp_ft_21',
 'md_nf_obgyn_subsp_pc_hosp_ft_20',
 'md_nf_obgyn_subsp_admin_21',
 'md_nf_obgyn_subsp_admin_20',
 'md_nf_obgyn_subsp_teach_21',
 'md_nf_obgyn_subsp_teach_20',
 'md_nf_obgyn_subsp_resrch_21',
 'md_nf_obgyn_subsp_resrch_20',
 'md_nf_obgyn_subsp_oth_21',
 'md_nf_obgyn_subsp_oth_20',
 'md_nf_ophth_21',
 'md_nf_ophth_20',
 'md_nf_ophth_all_pc_21',
 'md_nf_ophth_all_pc_20',
 'md_nf_ophth_pc_ofc_21',
 'md_nf_ophth_pc_ofc_20',
 'md_nf_ophth_pc_rsdnt_21',
 'md_nf_ophth_pc_rsdnt_20',
 'md_nf_ophth_pc_hosp_ft_21',
 'md_nf_ophth_pc_hosp_ft_20',
 'md_nf_ophth_admin_21',
 'md_nf_ophth_admin_20',
 'md_nf_ophth_teach_21',
 'md_nf_ophth_teach_20',
 'md_nf_ophth_resrch_21',
 'md_nf_ophth_resrch_20',
 'md_nf_ophth_oth_21',
 'md_nf_ophth_oth_20',
 'md_nf_ortho_21',
 'md_nf_ortho_20',
 'md_nf_ortho_all_pc_21',
 'md_nf_ortho_all_pc_20',
 'md_nf_ortho_pc_ofc_21',
 'md_nf_ortho_pc_ofc_20',
 'md_nf_ortho_pc_rsdnt_21',
 'md_nf_ortho_pc_rsdnt_20',
 'md_nf_ortho_pc_hosp_ft_21',
 'md_nf_ortho_pc_hosp_ft_20',
 'md_nf_ortho_admin_21',
 'md_nf_ortho_admin_20',
 'md_nf_ortho_teach_21',
 'md_nf_ortho_teach_20',
 'md_nf_ortho_resrch_21',
 'md_nf_ortho_resrch_20',
 'md_nf_ortho_oth_21',
 'md_nf_ortho_oth_20',
 'md_nf_otolryn_21',
 'md_nf_otolryn_20',
 'md_nf_otolryn_all_pc_21',
 'md_nf_otolryn_all_pc_20',
 'md_nf_otolryn_pc_ofc_21',
 'md_nf_otolryn_pc_ofc_20',
 'md_nf_otolryn_pc_rsdnt_21',
 'md_nf_otolryn_pc_rsdnt_20',
 'md_nf_otolryn_pc_hosp_ft_21',
 'md_nf_otolryn_pc_hosp_ft_20',
 'md_nf_otolryn_admin_21',
 'md_nf_otolryn_admin_20',
 'md_nf_otolryn_teach_21',
 'md_nf_otolryn_teach_20',
 'md_nf_otolryn_resrch_21',
 'md_nf_otolryn_resrch_20',
 'md_nf_otolryn_oth_21',
 'md_nf_otolryn_oth_20',
 'md_nf_plas_surg_21',
 'md_nf_plas_surg_20',
 'md_nf_plas_surg_all_pc_21',
 'md_nf_plas_surg_all_pc_20',
 'md_nf_plas_surg_pc_ofc_21',
 'md_nf_plas_surg_pc_ofc_20',
 'md_nf_plas_surg_pc_rsdnt_21',
 'md_nf_plas_surg_pc_rsdnt_20',
 'md_nf_plas_surg_pc_hosp_ft_21',
 'md_nf_plas_surg_pc_hosp_ft_20',
 'md_nf_plas_surg_admin_21',
 'md_nf_plas_surg_admin_20',
 'md_nf_plas_surg_teach_21',
 'md_nf_plas_surg_teach_20',
 'md_nf_plas_surg_resrch_21',
 'md_nf_plas_surg_resrch_20',
 'md_nf_plas_surg_oth_21',
 'md_nf_plas_surg_oth_20',
 'md_nf_colrct_surg_21',
 'md_nf_colrct_surg_20',
 'md_nf_colrct_surg_all_pc_21',
 'md_nf_colrct_surg_all_pc_20',
 'md_nf_colrct_surg_pc_ofc_21',
 'md_nf_colrct_surg_pc_ofc_20',
 'md_nf_colrct_surg_pc_rsdnt_21',
 'md_nf_colrct_surg_pc_rsdnt_20',
 'md_nf_colrct_surg_pc_hosp_ft_21',
 'md_nf_colrct_surg_pc_hosp_ft_20',
 'md_nf_colrct_surg_admin_21',
 'md_nf_colrct_surg_admin_20',
 'md_nf_colrct_surg_teach_21',
 'md_nf_colrct_surg_teach_20',
 'md_nf_colrct_surg_resrch_21',
 'md_nf_colrct_surg_resrch_20',
 'md_nf_colrct_surg_oth_21',
 'md_nf_colrct_surg_oth_20',
 'md_nf_thor_surg_21',
 'md_nf_thor_surg_20',
 'md_nf_thor_surg_all_pc_21',
 'md_nf_thor_surg_all_pc_20',
 'md_nf_thor_surg_pc_ofc_21',
 'md_nf_thor_surg_pc_ofc_20',
 'md_nf_thor_surg_pc_rsdnt_21',
 'md_nf_thor_surg_pc_rsdnt_20',
 'md_nf_thor_surg_pc_hosp_ft_21',
 'md_nf_thor_surg_pc_hosp_ft_20',
 'md_nf_thor_surg_admin_21',
 'md_nf_thor_surg_admin_20',
 'md_nf_thor_surg_teach_21',
 'md_nf_thor_surg_teach_20',
 'md_nf_thor_surg_resrch_21',
 'md_nf_thor_surg_resrch_20',
 'md_nf_thor_surg_oth_21',
 'md_nf_thor_surg_oth_20',
 'md_nf_urolgy_21',
 'md_nf_urolgy_20',
 'md_nf_urolgy_all_pc_21',
 'md_nf_urolgy_all_pc_20',
 'md_nf_urolgy_pc_ofc_21',
 'md_nf_urolgy_pc_ofc_20',
 'md_nf_urolgy_pc_rsdnt_21',
 'md_nf_urolgy_pc_rsdnt_20',
 'md_nf_urolgy_pc_hosp_ft_21',
 'md_nf_urolgy_pc_hosp_ft_20',
 'md_nf_urolgy_admin_21',
 'md_nf_urolgy_admin_20',
 'md_nf_urolgy_teach_21',
 'md_nf_urolgy_teach_20',
 'md_nf_urolgy_resrch_21',
 'md_nf_urolgy_resrch_20',
 'md_nf_urolgy_oth_21',
 'md_nf_urolgy_oth_20',
 'md_nf_all_oth_spec_21',
 'md_nf_all_oth_spec_20',
 'md_nf_all_oth_spec_all_pc_21',
 'md_nf_all_oth_spec_all_pc_20',
 'md_nf_all_oth_spec_pc_ofc_21',
 'md_nf_all_oth_spec_pc_ofc_20',
 'md_nf_all_oth_spec_pc_rsdnt_21',
 'md_nf_all_oth_spec_pc_rsdnt_20',
 'md_nf_all_oth_spec_pc_hosp_ft_21',
 'md_nf_all_oth_spec_pc_hosp_ft_20',
 'md_nf_all_oth_spec_admin_21',
 'md_nf_all_oth_spec_admin_20',
 'md_nf_all_oth_spec_teach_21',
 'md_nf_all_oth_spec_teach_20',
 'md_nf_all_oth_spec_resrch_21',
 'md_nf_all_oth_spec_resrch_20',
 'md_nf_all_oth_spec_oth_21',
 'md_nf_all_oth_spec_oth_20',
 'md_nf_aero_med_21',
 'md_nf_aero_med_20',
 'md_nf_aero_med_all_pc_21',
 'md_nf_aero_med_all_pc_20',
 'md_nf_aero_med_pc_ofc_21',
 'md_nf_aero_med_pc_ofc_20',
 'md_nf_aero_med_pc_rsdnt_21',
 'md_nf_aero_med_pc_rsdnt_20',
 'md_nf_aero_med_pc_hosp_ft_21',
 'md_nf_aero_med_pc_hosp_ft_20',
 'md_nf_aero_med_admin_21',
 'md_nf_aero_med_admin_20',
 'md_nf_aero_med_teach_21',
 'md_nf_aero_med_teach_20',
 'md_nf_aero_med_resrch_21',
 'md_nf_aero_med_resrch_20',
 'md_nf_aero_med_oth_21',
 'md_nf_aero_med_oth_20',
 'md_nf_anesth_21',
 'md_nf_anesth_20',
 'md_nf_anesth_all_pc_21',
 'md_nf_anesth_all_pc_20',
 'md_nf_anesth_pc_ofc_21',
 'md_nf_anesth_pc_ofc_20',
 'md_nf_anesth_pc_rsdnt_21',
 'md_nf_anesth_pc_rsdnt_20',
 'md_nf_anesth_pc_hosp_ft_21',
 'md_nf_anesth_pc_hosp_ft_20',
 'md_nf_anesth_admin_21',
 'md_nf_anesth_admin_20',
 'md_nf_anesth_teach_21',
 'md_nf_anesth_teach_20',
 'md_nf_anesth_resrch_21',
 'md_nf_anesth_resrch_20',
 'md_nf_anesth_oth_21',
 'md_nf_anesth_oth_20',
 'md_nf_child_psych_21',
 'md_nf_child_psych_20',
 'md_nf_child_psych_all_pc_21',
 'md_nf_child_psych_all_pc_20',
 'md_nf_child_psych_pc_ofc_21',
 'md_nf_child_psych_pc_ofc_20',
 'md_nf_child_psych_pc_rsdnt_21',
 'md_nf_child_psych_pc_rsdnt_20',
 'md_nf_child_psych_pc_hosp_ft_21',
 'md_nf_child_psych_pc_hosp_ft_20',
 'md_nf_child_psych_admin_21',
 'md_nf_child_psych_admin_20',
 'md_nf_child_psych_teach_21',
 'md_nf_child_psych_teach_20',
 'md_nf_child_psych_resrch_21',
 'md_nf_child_psych_resrch_20',
 'md_nf_child_psych_oth_21',
 'md_nf_child_psych_oth_20',
 'md_nf_diag_radlgy_21',
 'md_nf_diag_radlgy_20',
 'md_nf_diag_radlgy_all_pc_21',
 'md_nf_diag_radlgy_all_pc_20',
 'md_nf_diag_radlgy_pc_ofc_21',
 'md_nf_diag_radlgy_pc_ofc_20',
 'md_nf_diag_radlgy_pc_rsdnt_21',
 'md_nf_diag_radlgy_pc_rsdnt_20',
 'md_nf_diag_radlgy_pc_hosp_ft_21',
 'md_nf_diag_radlgy_pc_hosp_ft_20',
 'md_nf_diag_radlgy_admin_21',
 'md_nf_diag_radlgy_admin_20',
 'md_nf_diag_radlgy_teach_21',
 'md_nf_diag_radlgy_teach_20',
 'md_nf_diag_radlgy_resrch_21',
 'md_nf_diag_radlgy_resrch_20',
 'md_nf_diag_radlgy_oth_21',
 'md_nf_diag_radlgy_oth_20',
 'md_nf_emerg_med_21',
 'md_nf_emerg_med_20',
 'md_nf_emerg_med_all_pc_21',
 'md_nf_emerg_med_all_pc_20',
 'md_nf_emerg_med_pc_ofc_21',
 'md_nf_emerg_med_pc_ofc_20',
 'md_nf_emerg_med_pc_rsdnt_21',
 'md_nf_emerg_med_pc_rsdnt_20',
 'md_nf_emerg_med_pc_hosp_ft_21',
 'md_nf_emerg_med_pc_hosp_ft_20',
 'md_nf_emerg_med_admin_21',
 'md_nf_emerg_med_admin_20',
 'md_nf_emerg_med_teach_21',
 'md_nf_emerg_med_teach_20',
 'md_nf_emerg_med_resrch_21',
 'md_nf_emerg_med_resrch_20',
 'md_nf_emerg_med_oth_21',
 'md_nf_emerg_med_oth_20',
 'md_nf_foren_path_21',
 'md_nf_foren_path_20',
 'md_nf_foren_path_all_pc_21',
 'md_nf_foren_path_all_pc_20',
 'md_nf_foren_path_pc_ofc_21',
 'md_nf_foren_path_pc_ofc_20',
 'md_nf_foren_path_pc_rsdnt_21',
 'md_nf_foren_path_pc_rsdnt_20',
 'md_nf_foren_path_pc_hosp_ft_21',
 'md_nf_foren_path_pc_hosp_ft_20',
 'md_nf_foren_path_admin_21',
 'md_nf_foren_path_admin_20',
 'md_nf_foren_path_teach_21',
 'md_nf_foren_path_teach_20',
 'md_nf_foren_path_resrch_21',
 'md_nf_foren_path_resrch_20',
 'md_nf_foren_path_oth_21',
 'md_nf_foren_path_oth_20',
 'md_nf_med_gentcs_21',

In [148]:
mo_county_population = pd.read_csv("co-est2024-pop-29.csv", header=2, skipfooter = 6, engine='python')

mo_county_population = mo_county_population.rename(columns={
    'Population Estimate (as of July 1)': '2020 Population Estimate',
    'Unnamed: 3': '2021 Population Estimate',
    'Unnamed: 4': '2022 Population Estimate',
    'Unnamed: 5': '2023 Population Estimate',
    'Unnamed: 6': '2024 Population Estimate'
})

mo_county_population = mo_county_population.drop(0)

mo_county_population['Geographic Area'] = mo_county_population['Geographic Area'].str.replace('.', '', regex=False)
mo_county_population['Geographic Area'] = mo_county_population['Geographic Area'].str.replace(', Missouri', '', regex=False)
mo_county_population['Geographic Area'] = mo_county_population['Geographic Area'].str.replace(' County', '', regex=False).str.upper()
mo_county_population = mo_county_population.loc[:, ~mo_county_population.columns.str.contains('^Unnamed')]
mo_county_population = mo_county_population[mo_county_population['Geographic Area'] != 'MISSOURI']

mo_county_population = mo_county_population.reset_index(drop=True)

mo_county_population = mo_county_population[['Geographic Area', '2021 Population Estimate']]

mo_county_population

    Geographic Area 2021 Population Estimate
0             ADAIR                   25,188
1            ANDREW                   18,015
2          ATCHISON                    5,210
3           AUDRAIN                   24,858
4             BARRY                   34,762
..              ...                      ...
110           WAYNE                   10,925
111         WEBSTER                   39,600
112           WORTH                    1,973
113          WRIGHT                   18,625
114   ST LOUIS CITY                  293,484

[115 rows x 2 columns]

In [149]:
columns_to_keep = [
    'st_name_abbrev', 
    'cnty_name', 
    'phys_nf_prim_care_pc_exc_rsdt_21', 
]

pcp_df = ahrf_df[columns_to_keep].copy()

mo_pcp_df = pcp_df[pcp_df['st_name_abbrev'] == 'MO'].copy()
mo_pcp_df['cnty_name'] = mo_pcp_df['cnty_name'].str.upper()

merged_df = pd.merge(
    mo_pcp_df, 
    mo_county_population, 
    left_on='cnty_name', 
    right_on='Geographic Area', 
    how='inner'
)

merged_df = merged_df.drop(columns=['Geographic Area'])
merged_df = merged_df.drop(columns=['st_name_abbrev'])

merged_df = merged_df.rename(columns={
    'cnty_name': 'County',
    'phys_nf_prim_care_pc_exc_rsdt_21': 'Number of primary care providers'
})

merged_df['2021 Population Estimate'] = merged_df['2021 Population Estimate'].str.replace(',', '', regex=False)
merged_df['2021 Population Estimate'] = pd.to_numeric(merged_df['2021 Population Estimate'])

merged_df['primary care providers per 100k'] = (merged_df['Number of primary care providers'] / merged_df['2021 Population Estimate']) * 100000

In [150]:
merged_df.sort_values(by='primary care providers per 100k', ascending=False)

,County,Number of primary care providers,2021 Population Estimate,primary care providers per 100k
0,ADAIR,44.0,25188,174.686359
93,SCOTLAND,8.0,4674,171.159606
9,BOONE,220.0,186132,118.195689
63,MARION,29.0,28564,101.526397
11,BUTLER,40.0,42163,94.869910
...,...,...,...,...
27,CRAWFORD,1.0,22826,4.380969
43,HOLT,0.0,4234,0.000000
74,OREGON,0.0,8628,0.000000
51,KNOX,0.0,3786,0.000000
62,MARIES,0.0,8418,0.000000

In [151]:
percent_ovr_65_df

,County,FIPS,Value (Percent),People (Age 65 And Over),Rank within US (of 3143 counties)
0,United States,0.0,16.8,55970047.0,NaN
1,Missouri,29000.0,17.5,1079129.0,23 of 52
2,Pulaski County,29169.0,9.6,5169.0,"3,120"
3,Johnson County,29101.0,12.9,7013.0,"2,983"
4,Boone County,29019.0,13.1,24330.0,"2,964"
...,...,...,...,...,...
118,HDPulse: An Ecosystem of Minority Health and H...,NaN,NaN,NaN,NaN
119,Notes:,NaN,NaN,NaN,NaN
120,NA: Data not available [http://hdpulse.nimhd.n...,NaN,NaN,NaN,NaN
121,Source: Demographic data provided by the Censu...,NaN,NaN,NaN,NaN
122,For more information about Population (Age 65 ...,NaN,NaN,NaN,NaN

In [152]:
percent_ovr_65_df.columns

Index(['County', 'FIPS', 'Value (Percent)', 'People (Age 65 And Over)',
       'Rank within US (of 3143 counties)'],
      dtype='str')

In [156]:
percent_ovr_65_value_df = percent_ovr_65_df[['County', 'Value (Percent)']].copy()
percent_ovr_65_value_df = percent_ovr_65_value_df.rename(columns={
    'Value (Percent)': 'Percent of population over 65'
})
percent_ovr_65_value_df

,County,Percent of population over 65
0,United States,16.8
1,Missouri,17.5
2,Pulaski County,9.6
3,Johnson County,12.9
4,Boone County,13.1
...,...,...
118,HDPulse: An Ecosystem of Minority Health and H...,NaN
119,Notes:,NaN
120,NA: Data not available [http://hdpulse.nimhd.n...,NaN
121,Source: Demographic data provided by the Censu...,NaN
122,For more information about Population (Age 65 ...,NaN

In [157]:
percent_ovr_65_value_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 123 entries, 0 to 122
Data columns (total 2 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   County                         123 non-null    str
 1   Percent of population over 65  117 non-null    float64
dtypes: float64(1), str(1)
memory usage: 2.1 KB

In [161]:
unique_percents = percent_ovr_65_value_df['Percent of population over 65'].unique()
print(unique_percents)

[16.8 17.5  9.6 12.9 13.1 14.3 14.9 15.2 15.5 15.7 15.8 16.1 16.3 16.4
 16.9 17.1 17.2 17.3 17.4 17.8 17.9 18.  18.1 18.3 18.4 18.5 18.6 18.7
 18.8 18.9 19.  19.1 19.2 19.3 19.5 19.6 19.8 19.9 20.  20.1 20.2 20.4
 20.5 20.6 20.7 20.8 20.9 21.  21.2 21.7 21.8 21.9 22.  22.2 22.3 22.4
 22.6 22.8 22.9 23.3 23.6 24.3 24.5 24.7 25.  25.1 25.2 25.6 25.8 28.9
 29.  31.1 31.3 32.4  nan]

In [162]:
percent_ovr_65_cleaned = percent_ovr_65_value_df.dropna()

In [ ]:
percent_ovr_65_value_df.info()

In [164]:
percent_ovr_65_cleaned.sort_values(by='Percent of population over 65', ascending=False)

             County  Percent of population over 65
116  Hickory County                           32.4
115    Stone County                           31.3
114   Benton County                           31.1
113    Ozark County                           29.0
112   Camden County                           28.9
..              ...                            ...
6       Clay County                           14.9
5    Lincoln County                           14.3
4      Boone County                           13.1
3    Johnson County                           12.9
2    Pulaski County                            9.6

[117 rows x 2 columns]