In [8]:
import pandas as pd
import zipfile

In [17]:
vax_percent_df = pd.read_csv("County - Table_data.csv")

percent_ovr_65_df = pd.read_csv("Pop over 65%.csv",skiprows=4)

with zipfile.ZipFile('AHRF_CSV_2022-2023.zip', 'r') as z:
    with z.open('AHRF_CSV_2022-2023/DATA/ahrf2023.csv') as f:
        ahrf_df = pd.read_csv(f, encoding='latin1', low_memory=False)

In [5]:
vax_percent_df

    Jurisdiction             Measure Names  Measure Values
0         Wright  7-Day Doses Administered             0.0
1          Worth  7-Day Doses Administered             0.0
2        Webster  7-Day Doses Administered             0.0
3          Wayne  7-Day Doses Administered             0.0
4     Washington  7-Day Doses Administered             0.0
..           ...                       ...             ...
709        Barry  Total Doses Administered         30786.0
710      Audrain  Total Doses Administered         21387.0
711     Atchison  Total Doses Administered          5578.0
712       Andrew  Total Doses Administered         16437.0
713        Adair  Total Doses Administered         25027.0

[714 rows x 3 columns]

In [13]:
ahrf_df

,blank,fips_st_cnty,entity_file,secndry_entity_file,date_file,date_cretn,file_length,st_name,st_name_abbrev,cnty_name,...,dys_air_qulty_mesrd_21,dys_mesrd_air_qulty_good_22,dys_mesrd_air_qulty_good_21,good_air_qulty_dys_pct_22,good_air_qulty_dys_pct_21,annul_partclt_mattr_2_5_avg_19,annul_partclt_mattr_2_5_avg_18,dys_8_hr_ozone_over_naaqs_avg_19,dys_8_hr_ozone_over_naaqs_avg_18,elevtn_feet_76
0,NaN,1001,AHRF,1001,2023,23208,25907,Alabama,AL,Autauga,...,NaN,NaN,NaN,NaN,NaN,10.0,9.5,1.0,0.0,290.0
1,NaN,1003,AHRF,1003,2023,23208,25907,Alabama,AL,Baldwin,...,280.0,256.0,264.0,91.10,94.29,7.6,7.2,0.0,0.0,155.0
2,NaN,1005,AHRF,1005,2023,23208,25907,Alabama,AL,Barbour,...,NaN,NaN,NaN,NaN,NaN,9.4,9.0,0.0,0.0,220.0
3,NaN,1007,AHRF,1007,2023,23208,25907,Alabama,AL,Bibb,...,NaN,NaN,NaN,NaN,NaN,9.8,9.4,0.0,1.0,224.0
4,NaN,1009,AHRF,1009,2023,23208,25907,Alabama,AL,Blount,...,NaN,NaN,NaN,NaN,NaN,9.6,9.4,1.0,1.0,870.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3226,NaN,72151,AHRF,72151,2023,23208,25907,Puerto Rico,PR,Yabucoa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3227,NaN,72153,AHRF,72153,2023,23208,25907,Puerto Rico,PR,Yauco,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3228,NaN,78010,AHRF,78010,2023,23208,25907,US Virgin Islands,VI,St. Croix,...,55.0,23.0,52.0,88.46,94.55,6.3,NaN,NaN,NaN,NaN
3229,NaN,78020,AHRF,78020,2023,23208,25907,US Virgin Islands,VI,St. John,...,45.0,69.0,44.0,87.34,97.78,NaN,NaN,NaN,NaN,NaN
3230,NaN,78030,AHRF,78030,2023,23208,25907,US Virgin Islands,VI,St. Thomas,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
percent_ovr_65_df